name = "tales-genie"
account_id = "6d2e606929eb69f91f43b147615f1111"
routes = [
  { pattern = "talesgenie.parentsintech.org", custom_domain = true }
]
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2025-03-25"
compatibility_flags = [ "nodejs_compat" ]

[ai]
binding = "AI"

[observability]
enabled = true